input_up = keyboard_check(ord("W"))
input_left = keyboard_check(ord("A"))
input_right = keyboard_check(ord("D"))
input_down = keyboard_check(ord("S"))
input_release_up = keyboard_check_released(ord("W"))
input_release_down = keyboard_check_released(ord("S"))
input_space = keyboard_check_pressed(vk_space)
